version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '9000:8080'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5434/postgres'
      NODE_ENV: development
    links:
      - db
    volumes:
      - './:/src/app'
volumes:
  db:
    driver: local