version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-db-network
  nginx:
    image: nginx
    volumes: 
    - ./templates:/etc/nginx/templates
    ports:
        - "8080:80"
    networks: 
        - app-db-network
    depends_on:
        - "app"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '9000:9000'
    networks:
      - app-db-network
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      NODE_ENV: development
      PORT: 9000

    links:
      - db
    volumes:
      - './:/src/app'
volumes:
  db:
    driver: local
networks:
  app-db-network:
